const keywordData = [
  {keyword:'kitchen and toilet renovation',searchVol:50,cpc:0,category:'Full Bathroom Renovation'},
  {keyword:'kitchen renovation contractors',searchVol:50000,cpc:0.44,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath remodeling contractors near me',searchVol:5000,cpc:0.76,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation',searchVol:500000,cpc:1.04,category:'Full Kitchen Renovation'},
  {keyword:'kitchen reno',searchVol:500000,cpc:1.04,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodel contractors',searchVol:500000,cpc:1.08,category:'Full Kitchen Renovation'},
  {keyword:'contractor for kitchen remodel',searchVol:500000,cpc:1.08,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation services',searchVol:5000,cpc:0.84,category:'Full Kitchen Renovation'},
  {keyword:'kitchen makeovers',searchVol:50000,cpc:1.25,category:'Full Kitchen Renovation'},
  {keyword:'l shaped kitchen remodel',searchVol:500,cpc:0.64,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet refacers near me',searchVol:50000,cpc:0.44,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen and bathroom renovations',searchVol:5000,cpc:1.32,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath renovation',searchVol:5000,cpc:1.32,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodeling',searchVol:500000,cpc:1.75,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath contractors near me',searchVol:5000,cpc:1.45,category:'Full Kitchen Renovation'},
  {keyword:'kitchen redesign',searchVol:5000,cpc:1.56,category:'Full Kitchen Renovation'},
  {keyword:'bathroom remodel companies near me',searchVol:50000,cpc:0.74,category:'Full Bathroom Renovation'},
  {keyword:'bath remodeling companies near me',searchVol:50000,cpc:0.74,category:'Full Bathroom Renovation'},
  {keyword:'bath remodel contractors near me',searchVol:50000,cpc:0.74,category:'Full Bathroom Renovation'},
  {keyword:'bathroom remodel contractors',searchVol:500000,cpc:0.83,category:'Full Bathroom Renovation'},
  {keyword:'bathroom renovation contractors',searchVol:500000,cpc:0.83,category:'Full Bathroom Renovation'},
  {keyword:'remodeling bathroom contractors',searchVol:500000,cpc:0.83,category:'Full Bathroom Renovation'},
  {keyword:'luxury kitchen remodel',searchVol:5000,cpc:2.14,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet remodel',searchVol:500000,cpc:1.64,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen cabinet renovation',searchVol:500000,cpc:1.64,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen and bathroom contractors',searchVol:5000,cpc:2.31,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath contractors',searchVol:5000,cpc:2.31,category:'Full Kitchen Renovation'},
  {keyword:'modern kitchen remodel',searchVol:5000,cpc:2.62,category:'Full Kitchen Renovation'},
  {keyword:'modern kitchen renovation',searchVol:5000,cpc:2.62,category:'Full Kitchen Renovation'},
  {keyword:'small kitchen renovation',searchVol:5000,cpc:1.95,category:'Small Kitchen Renovation'},
  {keyword:'small kitchen reno',searchVol:5000,cpc:1.95,category:'Small Kitchen Renovation'},
  {keyword:'kitchen remodel cost',searchVol:50000,cpc:3.68,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation costs',searchVol:50000,cpc:3.68,category:'Full Kitchen Renovation'},
  {keyword:'kitchen redesign cost',searchVol:50000,cpc:3.68,category:'Full Kitchen Renovation'},
  {keyword:'kitchen reno cost',searchVol:50000,cpc:3.68,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodel prices',searchVol:50000,cpc:3.68,category:'Full Kitchen Renovation'},
  {keyword:'small kitchen makeovers',searchVol:5000,cpc:1.99,category:'Small Kitchen Renovation'},
  {keyword:'new kitchen cost',searchVol:5000,cpc:3.16,category:'Full Kitchen Renovation'},
  {keyword:'simple kitchen remodel',searchVol:500,cpc:2.15,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet makeover',searchVol:5000,cpc:1.85,category:'Partial Kitchen (Cabinets)'},
  {keyword:'white kitchen remodel',searchVol:500,cpc:2.23,category:'Full Kitchen Renovation'},
  {keyword:'planning a kitchen remodel',searchVol:5000,cpc:3.40,category:'Full Kitchen Renovation'},
  {keyword:'updating kitchen cabinets',searchVol:5000,cpc:1.97,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small kitchen remodel',searchVol:50000,cpc:3.24,category:'Small Kitchen Renovation'},
  {keyword:'top kitchen remodeling companies',searchVol:500,cpc:2.38,category:'Full Kitchen Renovation'},
  {keyword:'average cost of new kitchen',searchVol:500,cpc:2.99,category:'Full Kitchen Renovation'},
  {keyword:'kitchen upgrades on a budget',searchVol:500,cpc:2.47,category:'Full Kitchen Renovation'},
  {keyword:'raised ranch kitchen remodel',searchVol:500,cpc:3.86,category:'Full Kitchen Renovation'},
  {keyword:'average kitchen remodel cost',searchVol:5000,cpc:4.23,category:'Full Kitchen Renovation'},
  {keyword:'new kitchen remodel',searchVol:5000,cpc:4.29,category:'Full Kitchen Renovation'},
  {keyword:'kitchen upgrade cost',searchVol:5000,cpc:4.50,category:'Full Kitchen Renovation'},
  {keyword:'u shaped kitchen remodel',searchVol:500,cpc:4.10,category:'Full Kitchen Renovation'},
  {keyword:'new kitchen cabinets and countertops cost',searchVol:500,cpc:1.64,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen and bath remodeling',searchVol:50000,cpc:5.90,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bathroom remodeling',searchVol:50000,cpc:5.90,category:'Full Kitchen Renovation'},
  {keyword:'kitchen island makeover',searchVol:500,cpc:1.75,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen countertop makeover',searchVol:500,cpc:1.98,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small kitchen makeovers on a budget',searchVol:500,cpc:2.48,category:'Small Kitchen Renovation'},
  {keyword:'kitchen upgrade',searchVol:5000,cpc:5.27,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodel companies near me',searchVol:50000,cpc:7.59,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation companies near me',searchVol:50000,cpc:7.59,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodel near me',searchVol:500000,cpc:7.70,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation near me',searchVol:500000,cpc:7.70,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renovation services near me',searchVol:500,cpc:2.10,category:'Full Kitchen Renovation'},
  {keyword:'yelp kitchen remodel',searchVol:50,cpc:4.38,category:'Full Kitchen Renovation'},
  {keyword:'updating kitchen cabinets on a budget',searchVol:500,cpc:2.50,category:'Partial Kitchen (Cabinets)'},
  {keyword:'jacuzzi bathroom remodel',searchVol:50000,cpc:2.88,category:'Full Bathroom Renovation'},
  {keyword:'kitchen and bath remodeling contractors',searchVol:5000,cpc:4.74,category:'Full Kitchen Renovation'},
  {keyword:'new kitchen on a budget',searchVol:50,cpc:4.75,category:'Full Kitchen Renovation'},
  {keyword:'new small kitchen cost',searchVol:50,cpc:3.66,category:'Small Kitchen Renovation'},
  {keyword:'update kitchen countertops',searchVol:500,cpc:3.09,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small condo kitchen remodel',searchVol:500,cpc:3.86,category:'Small Kitchen Renovation'},
  {keyword:'new kitchen and bathroom',searchVol:500,cpc:5.79,category:'Full Kitchen Renovation'},
  {keyword:'quick kitchen remodel',searchVol:50,cpc:6.06,category:'Full Kitchen Renovation'},
  {keyword:'bathroom remodeling',searchVol:500000,cpc:4.10,category:'Full Bathroom Renovation'},
  {keyword:'bathroom reconstruction',searchVol:500000,cpc:4.10,category:'Full Bathroom Renovation'},
  {keyword:'bathroom remodel bathtub',searchVol:500000,cpc:4.10,category:'Full Bathroom Renovation'},
  {keyword:'kitchen remodel designer',searchVol:5000,cpc:9.39,category:'Full Kitchen Renovation'},
  {keyword:'remodeling your kitchen',searchVol:500,cpc:8.27,category:'Full Kitchen Renovation'},
  {keyword:'kitchen island remodel',searchVol:5000,cpc:4.77,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen cabinet refurbishing',searchVol:5000,cpc:4.90,category:'Partial Kitchen (Cabinets)'},
  {keyword:'remodel my kitchen',searchVol:500,cpc:8.69,category:'Full Kitchen Renovation'},
  {keyword:'renovate my kitchen',searchVol:500,cpc:8.69,category:'Full Kitchen Renovation'},
  {keyword:'townhouse kitchen remodel',searchVol:5000,cpc:8.64,category:'Full Kitchen Renovation'},
  {keyword:'jacuzzi bath remodel cost',searchVol:50000,cpc:5.45,category:'Full Bathroom Renovation'},
  {keyword:'new kitchen cabinets and countertops',searchVol:500,cpc:5.13,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small bathroom remodel',searchVol:50000,cpc:4.35,category:'Small Bathroom Renovation'},
  {keyword:'small bathroom renovations',searchVol:50000,cpc:4.35,category:'Small Bathroom Renovation'},
  {keyword:'small bathroom redo',searchVol:50000,cpc:4.35,category:'Small Bathroom Renovation'},
  {keyword:'bathroom remodels for small bathrooms',searchVol:50000,cpc:4.35,category:'Small Bathroom Renovation'},
  {keyword:'kitchen remodeling contractors near me',searchVol:50000,cpc:17.22,category:'Full Kitchen Renovation'},
  {keyword:'average bathroom remodel cost',searchVol:50000,cpc:5.95,category:'Full Bathroom Renovation'},
  {keyword:'typical bathroom remodel cost',searchVol:50000,cpc:5.95,category:'Full Bathroom Renovation'},
  {keyword:'average cost to redo a bathroom',searchVol:50000,cpc:5.95,category:'Full Bathroom Renovation'},
  {keyword:'san francisco kitchen remodel',searchVol:500,cpc:9.52,category:'Full Kitchen Renovation'},
  {keyword:'bathroom remodel cost',searchVol:50000,cpc:6.37,category:'Full Bathroom Renovation'},
  {keyword:'bathroom renovation cost',searchVol:50000,cpc:6.37,category:'Full Bathroom Renovation'},
  {keyword:'bath remodel cost',searchVol:50000,cpc:6.37,category:'Full Bathroom Renovation'},
  {keyword:'redoing kitchen cabinets',searchVol:500,cpc:6.16,category:'Partial Kitchen (Cabinets)'},
  {keyword:'replacing kitchen cabinets and countertops',searchVol:500,cpc:6.50,category:'Partial Kitchen (Cabinets)'},
  {keyword:'partial kitchen remodel',searchVol:500,cpc:6.69,category:'Partial Kitchen (Cabinets)'},
  {keyword:'partial kitchen renovation',searchVol:500,cpc:6.69,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small kitchen renovation cost',searchVol:5000,cpc:6.61,category:'Small Kitchen Renovation'},
  {keyword:'small kitchen remodel cost',searchVol:5000,cpc:6.61,category:'Small Kitchen Renovation'},
  {keyword:'kitchen cabinet refaced',searchVol:5000,cpc:6.83,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen countertop remodel',searchVol:5000,cpc:7.36,category:'Partial Kitchen (Cabinets)'},
  {keyword:'jacuzzi bath remodel',searchVol:50000,cpc:8.85,category:'Full Bathroom Renovation'},
  {keyword:'kitchen renovation specialist',searchVol:500,cpc:7.64,category:'Full Kitchen Renovation'},
  {keyword:'best bathroom remodelers near me',searchVol:5000,cpc:4.95,category:'Full Bathroom Renovation'},
  {keyword:'kitchen cabinet remodel cost',searchVol:500,cpc:4.62,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen cabinet renovation cost',searchVol:500,cpc:4.62,category:'Partial Kitchen (Cabinets)'},
  {keyword:'full kitchen remodel cost',searchVol:500,cpc:10.04,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet resurfacing cost',searchVol:500,cpc:6.10,category:'Partial Kitchen (Cabinets)'},
  {keyword:'new kitchen renovation',searchVol:50,cpc:10.24,category:'Full Kitchen Renovation'},
  {keyword:'tub to shower conversion',searchVol:50000,cpc:11.58,category:'Full Bathroom Renovation'},
  {keyword:'bathtub to shower conversion',searchVol:50000,cpc:11.58,category:'Full Bathroom Renovation'},
  {keyword:'bathroom tub to shower conversion',searchVol:50000,cpc:11.58,category:'Full Bathroom Renovation'},
  {keyword:'converting a tub into a shower',searchVol:50000,cpc:11.58,category:'Full Bathroom Renovation'},
  {keyword:'shower to bathtub conversion',searchVol:50000,cpc:11.58,category:'Full Bathroom Renovation'},
  {keyword:'kitchen contractors near me',searchVol:5000,cpc:12.04,category:'Full Kitchen Renovation'},
  {keyword:'kitchen upgrade near me',searchVol:500,cpc:12.29,category:'Full Kitchen Renovation'},
  {keyword:'best kitchen remodelers near me',searchVol:5000,cpc:12.51,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet contractor',searchVol:500,cpc:7.60,category:'Partial Kitchen (Cabinets)'},
  {keyword:'new kitchen remodel cost',searchVol:50,cpc:12.64,category:'Full Kitchen Renovation'},
  {keyword:'new kitchen renovation cost',searchVol:50,cpc:12.64,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodel designer near me',searchVol:500,cpc:13.57,category:'Full Kitchen Renovation'},
  {keyword:'bathroom remodel near me',searchVol:500000,cpc:17.62,category:'Full Bathroom Renovation'},
  {keyword:'bathroom renovations near me',searchVol:500000,cpc:17.62,category:'Full Bathroom Renovation'},
  {keyword:'bath renovation near me',searchVol:500000,cpc:17.62,category:'Full Bathroom Renovation'},
  {keyword:'kitchen countertop remodel cost',searchVol:500,cpc:8.64,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen tune up prices',searchVol:50,cpc:8.62,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen renewal',searchVol:500,cpc:9.11,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen pantry remodel',searchVol:500,cpc:9.36,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen and bath companies near me',searchVol:500,cpc:15.70,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath remodeling near me',searchVol:5000,cpc:16.18,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bathroom remodel near me',searchVol:5000,cpc:16.18,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath renovation near me',searchVol:500,cpc:16.18,category:'Full Kitchen Renovation'},
  {keyword:'kitchen and bath remodel near me',searchVol:500,cpc:16.18,category:'Full Kitchen Renovation'},
  {keyword:'kitchen remodelers in my area',searchVol:500,cpc:17.21,category:'Full Kitchen Renovation'},
  {keyword:'kitchen renewal cost',searchVol:50,cpc:11.00,category:'Partial Kitchen (Cabinets)'},
  {keyword:'best kitchen and bath remodelers near me',searchVol:5000,cpc:19.36,category:'Full Kitchen Renovation'},
  {keyword:'kitchen tune up near me',searchVol:500,cpc:12.05,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen tune up cost',searchVol:50,cpc:13.21,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen floor remodel',searchVol:500,cpc:22.50,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet makeover near me',searchVol:500,cpc:13.99,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen and bath restoration',searchVol:50,cpc:25.45,category:'Full Kitchen Renovation'},
  {keyword:'top kitchen remodelers near me',searchVol:50,cpc:28.27,category:'Full Kitchen Renovation'},
  {keyword:'reasonable kitchen remodel',searchVol:50,cpc:28.66,category:'Full Kitchen Renovation'},
  {keyword:'kitchen cabinet refurbishing near me',searchVol:50,cpc:19.54,category:'Partial Kitchen (Cabinets)'},
  {keyword:'kitchen renewal near me',searchVol:50,cpc:20.04,category:'Partial Kitchen (Cabinets)'},
  {keyword:'small bathroom remodel cost',searchVol:5000,cpc:7.28,category:'Small Bathroom Renovation'},
  {keyword:'one day bathroom remodel',searchVol:5000,cpc:22.10,category:'Full Bathroom Renovation'}
];
