const keywordData = [
  {keyword:'kitchen remodeling',searchVol:210,cpc:23.24,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'bathroom remodeling',searchVol:390,cpc:28.82,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'roofing',searchVol:320,cpc:64.0,category:'Roofing'},
  {keyword:'hvac',searchVol:390,cpc:42.0,category:'HVAC'},
  {keyword:'pool resurfacing',searchVol:170,cpc:31.55,category:'Pool Services'},
  {keyword:'concrete',searchVol:260,cpc:11.67,category:'Concrete'},
  {keyword:'deck building',searchVol:40,cpc:18.5,category:'Deck & Outdoor'},
  {keyword:'pressure washing',searchVol:1000,cpc:3.3,category:'Pressure Washing'},
  {keyword:'epoxy flooring',searchVol:90,cpc:17.33,category:'Flooring'},
  {keyword:'roofing companies near me',searchVol:880,cpc:82.0,category:'Roofing'},
  {keyword:'roofers near me',searchVol:720,cpc:87.78,category:'Roofing'},
  {keyword:'ac repair near me',searchVol:1900,cpc:79.59,category:'HVAC'},
  {keyword:'hvac near me',searchVol:260,cpc:92.71,category:'HVAC'},
  {keyword:'jacuzzi bath remodel',searchVol:210,cpc:13.02,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'ac repair',searchVol:1900,cpc:70.0,category:'HVAC'},
  {keyword:'air conditioner repair',searchVol:1900,cpc:70.0,category:'HVAC'},
  {keyword:'heating and cooling near me',searchVol:260,cpc:92.71,category:'HVAC'},
  {keyword:'roof repair near me',searchVol:720,cpc:86.04,category:'Roofing'},
  {keyword:'metal roofing',searchVol:260,cpc:30.0,category:'Roofing'},
  {keyword:'roof repair',searchVol:210,cpc:70.0,category:'Roofing'},
  {keyword:'epoxy garage floor',searchVol:210,cpc:16.8,category:'Flooring'},
  {keyword:'bathroom remodel near me',searchVol:320,cpc:38.05,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'hvac repair near me',searchVol:170,cpc:70.0,category:'HVAC'},
  {keyword:'roofing contractors near me',searchVol:880,cpc:82.0,category:'Roofing'},
  {keyword:'deck builders near me',searchVol:30,cpc:19.73,category:'Deck & Outdoor'},
  {keyword:'hvac companies near me',searchVol:170,cpc:56.25,category:'HVAC'},
  {keyword:'air conditioner repair near me',searchVol:1900,cpc:79.59,category:'HVAC'},
  {keyword:'power washing near me',searchVol:720,cpc:16.0,category:'Pressure Washing'},
  {keyword:'roof replacement cost',searchVol:30,cpc:39.42,category:'Roofing'},
  {keyword:'ductless air conditioner',searchVol:90,cpc:5.38,category:'HVAC'},
  {keyword:'bathroom renovations',searchVol:50,cpc:34.59,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'shower remodel',searchVol:40,cpc:30.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'roofing companies',searchVol:260,cpc:82.0,category:'Roofing'},
  {keyword:'bathroom remodel cost',searchVol:70,cpc:9.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'karcher pressure washer',searchVol:40,cpc:1.15,category:'Pressure Washing'},
  {keyword:'concrete contractors near me',searchVol:260,cpc:10.83,category:'Concrete'},
  {keyword:'garage floor coating',searchVol:170,cpc:11.99,category:'Flooring'},
  {keyword:'power washer',searchVol:170,cpc:5.72,category:'Pressure Washing'},
  {keyword:'pressure washing near me',searchVol:720,cpc:16.0,category:'Pressure Washing'},
  {keyword:'best roofing company near me',searchVol:40,cpc:56.42,category:'Roofing'},
  {keyword:'concrete companies near me',searchVol:90,cpc:21.28,category:'Concrete'},
  {keyword:'air conditioner service',searchVol:140,cpc:77.0,category:'HVAC'},
  {keyword:'garage flooring',searchVol:70,cpc:19.35,category:'Flooring'},
  {keyword:'air conditioning',searchVol:260,cpc:55.18,category:'HVAC'},
  {keyword:'jacuzzi bath remodel cost',searchVol:70,cpc:10.45,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'ac company near me',searchVol:1000,cpc:70.07,category:'HVAC'},
  {keyword:'kitchen remodel near me',searchVol:210,cpc:32.58,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'concrete repair near me',searchVol:70,cpc:25.0,category:'Concrete'},
  {keyword:'kitchen renovation',searchVol:30,cpc:40.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'metal roof cost',searchVol:70,cpc:15.86,category:'Roofing'},
  {keyword:'ac tune up near me',searchVol:50,cpc:57.82,category:'HVAC'},
  {keyword:'electric pressure washer',searchVol:210,cpc:0.84,category:'Pressure Washing'},
  {keyword:'roof leak repair',searchVol:70,cpc:80.0,category:'Roofing'},
  {keyword:'air conditioning companies near me',searchVol:140,cpc:75.2,category:'HVAC'},
  {keyword:'central air conditioner',searchVol:90,cpc:24.73,category:'HVAC'},
  {keyword:'ready mix concrete',searchVol:40,cpc:3.85,category:'Concrete'},
  {keyword:'mitsubishi air conditioner',searchVol:20,cpc:4.61,category:'HVAC'},
  {keyword:'tub to shower conversion',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'epoxy floor coating',searchVol:70,cpc:10.13,category:'Flooring'},
  {keyword:'roof maxx',searchVol:90,cpc:14.01,category:'Roofing'},
  {keyword:'air conditioner service near me',searchVol:720,cpc:85.6,category:'HVAC'},
  {keyword:'hvac service',searchVol:50,cpc:50.0,category:'HVAC'},
  {keyword:'kitchen remodel cost',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'concrete near me',searchVol:50,cpc:17.07,category:'Concrete'},
  {keyword:'concrete repair',searchVol:30,cpc:23.15,category:'Concrete'},
  {keyword:'small bathroom remodel',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'standing seam metal roof',searchVol:170,cpc:23.46,category:'Roofing'},
  {keyword:'air conditioner installation',searchVol:210,cpc:50.0,category:'HVAC'},
  {keyword:'ac installation',searchVol:210,cpc:50.0,category:'HVAC'},
  {keyword:'ac unit cost',searchVol:20,cpc:10.02,category:'HVAC'},
  {keyword:'epoxy flooring near me',searchVol:70,cpc:23.93,category:'Flooring'},
  {keyword:'emergency ac repair near me',searchVol:50,cpc:82.99,category:'HVAC'},
  {keyword:'cement mixer',searchVol:40,cpc:8.61,category:'Concrete'},
  {keyword:'new ac unit cost',searchVol:20,cpc:17.95,category:'HVAC'},
  {keyword:'trane air conditioner',searchVol:90,cpc:14.89,category:'HVAC'},
  {keyword:'ac maintenance',searchVol:320,cpc:70.0,category:'HVAC'},
  {keyword:'concrete mixer',searchVol:90,cpc:4.94,category:'Concrete'},
  {keyword:'hvac system',searchVol:50,cpc:22.36,category:'HVAC'},
  {keyword:'bathroom renovation cost',searchVol:70,cpc:9.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'tpo roofing',searchVol:50,cpc:19.28,category:'Roofing'},
  {keyword:'best roofers near me',searchVol:50,cpc:70.28,category:'Roofing'},
  {keyword:'hvac companies',searchVol:50,cpc:44.45,category:'HVAC'},
  {keyword:'roof shingles',searchVol:90,cpc:18.84,category:'Roofing'},
  {keyword:'gaf shingles',searchVol:40,cpc:15.06,category:'Roofing'},
  {keyword:'electric power washer',searchVol:70,cpc:0.9,category:'Pressure Washing'},
  {keyword:'goodman ac unit',searchVol:30,cpc:12.19,category:'HVAC'},
  {keyword:'epdm roofing',searchVol:20,cpc:25.91,category:'Roofing'},
  {keyword:'best pressure washer',searchVol:50,cpc:0.97,category:'Pressure Washing'},
  {keyword:'carrier ac unit',searchVol:70,cpc:13.77,category:'HVAC'},
  {keyword:'polished concrete floors',searchVol:50,cpc:7.2,category:'Flooring'},
  {keyword:'metal roofing companies near me',searchVol:40,cpc:81.24,category:'Roofing'},
  {keyword:'concrete stain',searchVol:70,cpc:4.06,category:'Concrete'},
  {keyword:'polyaspartic floor coating',searchVol:70,cpc:17.73,category:'Flooring'},
  {keyword:'roof leak repair near me',searchVol:90,cpc:94.73,category:'Roofing'},
  {keyword:'goodman air conditioner',searchVol:90,cpc:13.32,category:'HVAC'},
  {keyword:'concrete driveway',searchVol:50,cpc:16.41,category:'Concrete'},
  {keyword:'best electric pressure washer',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'stamped concrete patio',searchVol:40,cpc:6.69,category:'Concrete'},
  {keyword:'metal roof installers near me',searchVol:40,cpc:81.24,category:'Roofing'},
  {keyword:'stamped concrete',searchVol:70,cpc:11.33,category:'Concrete'},
  {keyword:'roof inspection',searchVol:70,cpc:63.93,category:'Roofing'},
  {keyword:'hvac maintenance',searchVol:50,cpc:44.14,category:'HVAC'},
  {keyword:'concrete resurfacing',searchVol:40,cpc:12.4,category:'Concrete'},
  {keyword:'rheem air conditioner',searchVol:90,cpc:17.68,category:'HVAC'},
  {keyword:'bathroom renovations near me',searchVol:320,cpc:38.05,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'air conditioning companies',searchVol:720,cpc:75.19,category:'HVAC'},
  {keyword:'decks',searchVol:90,cpc:2.69,category:'Deck & Outdoor'},
  {keyword:'bathroom remodel contractors near me',searchVol:20,cpc:33.84,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'concrete pavers',searchVol:70,cpc:5.93,category:'Concrete'},
  {keyword:'abc roofing',searchVol:50,cpc:24.47,category:'Roofing'},
  {keyword:'epoxy garage floor cost',searchVol:40,cpc:16.32,category:'Flooring'},
  {keyword:'concrete driveway repair',searchVol:40,cpc:25.0,category:'Concrete'},
  {keyword:'roof maxx cost',searchVol:30,cpc:15.28,category:'Roofing'},
  {keyword:'pool resurfacing near me',searchVol:110,cpc:42.23,category:'Pool Services'},
  {keyword:'metal shingles',searchVol:70,cpc:17.35,category:'Roofing'},
  {keyword:'bath fitter near me',searchVol:20,cpc:34.21,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'emergency air conditioner repair',searchVol:70,cpc:91.29,category:'HVAC'},
  {keyword:'ars air conditioning',searchVol:20,cpc:54.98,category:'HVAC'},
  {keyword:'driveway resurfacing',searchVol:50,cpc:15.82,category:'Concrete'},
  {keyword:'garage floor coating near me',searchVol:20,cpc:19.35,category:'Flooring'},
  {keyword:'concrete patio',searchVol:30,cpc:6.58,category:'Concrete'},
  {keyword:'bathtub to shower conversion',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'metal roofing contractors near me',searchVol:40,cpc:81.24,category:'Roofing'},
  {keyword:'cement contractors near me',searchVol:260,cpc:10.83,category:'Concrete'},
  {keyword:'carrier hvac',searchVol:20,cpc:21.15,category:'HVAC'},
  {keyword:'one hour heating and cooling',searchVol:110,cpc:48.17,category:'HVAC'},
  {keyword:'heating and air repair near me',searchVol:170,cpc:70.0,category:'HVAC'},
  {keyword:'trane ac unit',searchVol:50,cpc:12.97,category:'HVAC'},
  {keyword:'kitchen renovation costs',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'air conditioner maintenance near me',searchVol:390,cpc:55.79,category:'HVAC'},
  {keyword:'concrete driveway cost',searchVol:20,cpc:5.94,category:'Concrete'},
  {keyword:'commercial pressure washer',searchVol:90,cpc:6.68,category:'Pressure Washing'},
  {keyword:'concrete coatings',searchVol:20,cpc:11.28,category:'Concrete'},
  {keyword:'metal roofing prices',searchVol:70,cpc:15.86,category:'Roofing'},
  {keyword:'pool remodeling near me',searchVol:110,cpc:34.15,category:'Pool Services'},
  {keyword:'corrugated metal',searchVol:30,cpc:14.09,category:'General Contracting'},
  {keyword:'powerwasher',searchVol:20,cpc:10.4,category:'Pressure Washing'},
  {keyword:'air conditioner near me',searchVol:140,cpc:57.17,category:'HVAC'},
  {keyword:'central ac unit',searchVol:30,cpc:21.57,category:'HVAC'},
  {keyword:'metal roof shingles',searchVol:70,cpc:17.35,category:'Roofing'},
  {keyword:'new air conditioner cost',searchVol:20,cpc:14.61,category:'HVAC'},
  {keyword:'central air conditioning unit',searchVol:30,cpc:21.57,category:'HVAC'},
  {keyword:'best power washer',searchVol:50,cpc:0.97,category:'Pressure Washing'},
  {keyword:'best electric power washer',searchVol:20,cpc:1.19,category:'Pressure Washing'},
  {keyword:'concrete polishing',searchVol:40,cpc:6.03,category:'Concrete'},
  {keyword:'simpson pressure washer',searchVol:50,cpc:1.2,category:'Pressure Washing'},
  {keyword:'pressure washing services near me',searchVol:720,cpc:16.0,category:'Pressure Washing'},
  {keyword:'concrete company',searchVol:30,cpc:27.0,category:'Concrete'},
  {keyword:'honda pressure washer',searchVol:50,cpc:0.63,category:'Pressure Washing'},
  {keyword:'kitchen renovation near me',searchVol:210,cpc:32.58,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'power washing companies near me',searchVol:720,cpc:16.0,category:'Pressure Washing'},
  {keyword:'bathroom remodel companies',searchVol:20,cpc:22.2,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'corrugated metal roofing',searchVol:20,cpc:23.66,category:'Roofing'},
  {keyword:'shower renovation',searchVol:40,cpc:30.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'concrete driveway contractors near me',searchVol:20,cpc:11.8,category:'Concrete'},
  {keyword:'concrete crack repair',searchVol:20,cpc:5.62,category:'Concrete'},
  {keyword:'service experts heating & air conditioning',searchVol:170,cpc:16.21,category:'HVAC'},
  {keyword:'apex roofing',searchVol:20,cpc:31.59,category:'Roofing'},
  {keyword:'central air conditioning system',searchVol:90,cpc:24.73,category:'HVAC'},
  {keyword:'ac contractors near me',searchVol:20,cpc:65.08,category:'HVAC'},
  {keyword:'concrete slab',searchVol:40,cpc:13.04,category:'Concrete'},
  {keyword:'certainteed shingles',searchVol:20,cpc:18.59,category:'Roofing'},
  {keyword:'pressure washing business',searchVol:20,cpc:13.0,category:'Pressure Washing'},
  {keyword:'air conditioner tune up near me',searchVol:50,cpc:57.82,category:'HVAC'},
  {keyword:'new air conditioning unit',searchVol:20,cpc:27.03,category:'HVAC'},
  {keyword:'owens corning shingles',searchVol:40,cpc:12.0,category:'Roofing'},
  {keyword:'concrete driveway contractors',searchVol:40,cpc:16.4,category:'Concrete'},
  {keyword:'rhino roofing',searchVol:170,cpc:18.55,category:'Roofing'},
  {keyword:'bathroom remodel companies near me',searchVol:20,cpc:33.84,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'power wash house',searchVol:20,cpc:10.19,category:'Pressure Washing'},
  {keyword:'reliable roofing',searchVol:30,cpc:32.54,category:'Roofing'},
  {keyword:'readymix concrete',searchVol:40,cpc:3.85,category:'Concrete'},
  {keyword:'ac unit for house',searchVol:40,cpc:17.92,category:'HVAC'},
  {keyword:'pressure cleaning',searchVol:110,cpc:15.61,category:'Pressure Washing'},
  {keyword:'leaking roof',searchVol:20,cpc:69.04,category:'Roofing'},
  {keyword:'hvac installer',searchVol:20,cpc:58.89,category:'HVAC'},
  {keyword:'roof inspection near me',searchVol:30,cpc:67.6,category:'Roofing'},
  {keyword:'trane ac',searchVol:90,cpc:14.89,category:'HVAC'},
  {keyword:'kitchen and bath remodeling',searchVol:30,cpc:19.11,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'american standard air conditioner',searchVol:50,cpc:9.56,category:'HVAC'},
  {keyword:'average bathroom remodel cost',searchVol:20,cpc:9.65,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'roof seal',searchVol:20,cpc:12.81,category:'Roofing'},
  {keyword:'concrete grinding',searchVol:40,cpc:3.0,category:'Concrete'},
  {keyword:'aluminum roofing',searchVol:20,cpc:19.66,category:'Roofing'},
  {keyword:'carrier heating and cooling',searchVol:20,cpc:21.15,category:'HVAC'},
  {keyword:'air conditioning tune up',searchVol:50,cpc:62.56,category:'HVAC'},
  {keyword:'home depot pressure washer',searchVol:140,cpc:0.74,category:'Pressure Washing'},
  {keyword:'one hour heating & air conditioning',searchVol:110,cpc:48.17,category:'HVAC'},
  {keyword:'asphalt shingles',searchVol:70,cpc:20.61,category:'Roofing'},
  {keyword:'ferguson hvac',searchVol:40,cpc:15.67,category:'HVAC'},
  {keyword:'advanced roofing',searchVol:40,cpc:19.84,category:'Roofing'},
  {keyword:'home ac unit',searchVol:40,cpc:17.92,category:'HVAC'},
  {keyword:'portable pressure washer',searchVol:30,cpc:1.59,category:'Pressure Washing'},
  {keyword:'kitchen and bathroom remodeling',searchVol:30,cpc:19.11,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'roof painting',searchVol:20,cpc:15.78,category:'Roofing'},
  {keyword:'emergency ac repair',searchVol:70,cpc:91.29,category:'HVAC'},
  {keyword:'concrete slab cost',searchVol:20,cpc:6.43,category:'Concrete'},
  {keyword:'pressure washer trailer',searchVol:30,cpc:4.7,category:'Pressure Washing'},
  {keyword:'pressure washing companies near me',searchVol:70,cpc:16.71,category:'Pressure Washing'},
  {keyword:'carrier air conditioning',searchVol:90,cpc:24.87,category:'HVAC'},
  {keyword:'trane hvac',searchVol:20,cpc:26.63,category:'HVAC'},
  {keyword:'power washer home depot',searchVol:30,cpc:0.82,category:'Pressure Washing'},
  {keyword:'polyaspartic garage floor coating',searchVol:20,cpc:19.25,category:'Flooring'},
  {keyword:'milwaukee pressure washer',searchVol:20,cpc:0.79,category:'Pressure Washing'},
  {keyword:'york air conditioner',searchVol:20,cpc:22.07,category:'HVAC'},
  {keyword:'bath remodeling companies',searchVol:20,cpc:22.2,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'soft wash roof cleaning',searchVol:30,cpc:13.78,category:'Roofing'},
  {keyword:'bath remodel cost',searchVol:70,cpc:9.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pressure wash house',searchVol:20,cpc:10.19,category:'Pressure Washing'},
  {keyword:'cost to replace ac unit',searchVol:30,cpc:21.69,category:'HVAC'},
  {keyword:'wall mounted pressure washer',searchVol:20,cpc:4.99,category:'Pressure Washing'},
  {keyword:'hydraulic cement',searchVol:40,cpc:1.05,category:'Concrete'},
  {keyword:'power washer for sale',searchVol:30,cpc:1.13,category:'Pressure Washing'},
  {keyword:'pressure cleaning near me',searchVol:720,cpc:16.0,category:'Pressure Washing'},
  {keyword:'concrete flooring',searchVol:30,cpc:25.39,category:'Flooring'},
  {keyword:'pool resurfacing cost',searchVol:50,cpc:18.72,category:'Pool Services'},
  {keyword:'concrete acid stain',searchVol:20,cpc:2.74,category:'HVAC'},
  {keyword:'trane air conditioner prices',searchVol:20,cpc:6.79,category:'HVAC'},
  {keyword:'roof cleaning services near me',searchVol:30,cpc:17.45,category:'Roofing'},
  {keyword:'architectural shingles',searchVol:50,cpc:42.08,category:'Roofing'},
  {keyword:'trane ac unit cost',searchVol:20,cpc:6.79,category:'HVAC'},
  {keyword:'replace ac unit',searchVol:90,cpc:51.59,category:'HVAC'},
  {keyword:'metallic epoxy floor',searchVol:20,cpc:9.03,category:'Flooring'},
  {keyword:'rheem ac unit',searchVol:20,cpc:7.51,category:'HVAC'},
  {keyword:'hvac emergency repair',searchVol:70,cpc:91.29,category:'HVAC'},
  {keyword:'pressure washing prices',searchVol:20,cpc:9.69,category:'Pressure Washing'},
  {keyword:'standing seam roof',searchVol:20,cpc:23.43,category:'Roofing'},
  {keyword:'bathroom renovation contractors near me',searchVol:320,cpc:38.05,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'concrete overlay',searchVol:20,cpc:3.13,category:'Concrete'},
  {keyword:'iko shingles',searchVol:20,cpc:7.03,category:'Roofing'},
  {keyword:'comfort air conditioning',searchVol:20,cpc:29.01,category:'HVAC'},
  {keyword:'wall unit air conditioner',searchVol:90,cpc:3.77,category:'HVAC'},
  {keyword:'american standard ac',searchVol:50,cpc:9.56,category:'HVAC'},
  {keyword:'ductwork',searchVol:30,cpc:21.26,category:'HVAC'},
  {keyword:'soffits and fascia',searchVol:30,cpc:15.77,category:'Roofing'},
  {keyword:'air handler unit',searchVol:30,cpc:11.05,category:'HVAC'},
  {keyword:'pressure washing company',searchVol:50,cpc:27.54,category:'Pressure Washing'},
  {keyword:'roof r',searchVol:20,cpc:11.88,category:'Roofing'},
  {keyword:'power washing company',searchVol:50,cpc:27.54,category:'Pressure Washing'},
  {keyword:'gaf roofing shingles',searchVol:40,cpc:15.06,category:'Roofing'},
  {keyword:'concrete patch',searchVol:20,cpc:3.48,category:'Concrete'},
  {keyword:'bath renovation',searchVol:50,cpc:34.59,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'soft wash',searchVol:40,cpc:2.9,category:'Pressure Washing'},
  {keyword:'power washing business',searchVol:20,cpc:13.0,category:'Pressure Washing'},
  {keyword:'best roofing',searchVol:20,cpc:24.71,category:'Roofing'},
  {keyword:'stamped concrete driveway',searchVol:30,cpc:8.32,category:'Concrete'},
  {keyword:'sunjoe power washer',searchVol:20,cpc:1.23,category:'Pressure Washing'},
  {keyword:'slate roof',searchVol:30,cpc:30.57,category:'Roofing'},
  {keyword:'driveway pressure washing',searchVol:50,cpc:10.46,category:'Pressure Washing'},
  {keyword:'ac unit maintenance',searchVol:320,cpc:70.0,category:'HVAC'},
  {keyword:'aluminum roof',searchVol:20,cpc:19.66,category:'Roofing'},
  {keyword:'air conditioner repair service near me',searchVol:720,cpc:85.6,category:'HVAC'},
  {keyword:'bathtub conversion to shower',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'honda power washer',searchVol:30,cpc:1.07,category:'Pressure Washing'},
  {keyword:'painting garage floor',searchVol:170,cpc:11.99,category:'Flooring'},
  {keyword:'portable power washer',searchVol:30,cpc:1.59,category:'Pressure Washing'},
  {keyword:'tamko shingles',searchVol:20,cpc:30.58,category:'Roofing'},
  {keyword:'bath renovation near me',searchVol:320,cpc:38.05,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'best pressure washer for home use',searchVol:20,cpc:0.89,category:'Pressure Washing'},
  {keyword:'metal roof installation',searchVol:30,cpc:61.42,category:'Roofing'},
  {keyword:'ryobi power washer',searchVol:20,cpc:1.17,category:'Pressure Washing'},
  {keyword:'small bathroom renovations',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'best power washer for home use',searchVol:20,cpc:0.89,category:'Pressure Washing'},
  {keyword:'affordable air conditioning',searchVol:20,cpc:44.47,category:'HVAC'},
  {keyword:'steel roof cost',searchVol:70,cpc:15.86,category:'Roofing'},
  {keyword:'kitchen reno',searchVol:30,cpc:40.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'replace air conditioner',searchVol:90,cpc:51.59,category:'HVAC'},
  {keyword:'quikrete concrete mix',searchVol:20,cpc:1.79,category:'Concrete'},
  {keyword:'rrca roofing',searchVol:20,cpc:17.09,category:'Roofing'},
  {keyword:'air conditioner unit cost',searchVol:20,cpc:10.02,category:'HVAC'},
  {keyword:'air conditioner maintenance',searchVol:320,cpc:70.0,category:'HVAC'},
  {keyword:'bath remodeling companies near me',searchVol:20,cpc:33.84,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'patio roofing',searchVol:20,cpc:12.44,category:'Roofing'},
  {keyword:'concrete price per yard',searchVol:20,cpc:3.0,category:'Concrete'},
  {keyword:'steel shingles',searchVol:70,cpc:17.35,category:'Roofing'},
  {keyword:'jb roofing',searchVol:30,cpc:30.42,category:'Roofing'},
  {keyword:'roof power washing',searchVol:30,cpc:27.63,category:'Roofing'},
  {keyword:'cost of concrete per yard',searchVol:20,cpc:3.0,category:'Concrete'},
  {keyword:'owens corning roofing',searchVol:40,cpc:12.0,category:'Roofing'},
  {keyword:'cost to replace air conditioner',searchVol:30,cpc:21.69,category:'HVAC'},
  {keyword:'simpson power washer',searchVol:50,cpc:1.2,category:'Pressure Washing'},
  {keyword:'rheem air conditioner prices',searchVol:20,cpc:7.0,category:'HVAC'},
  {keyword:'small pressure washer',searchVol:20,cpc:1.14,category:'Pressure Washing'},
  {keyword:'best ac companies near me',searchVol:40,cpc:48.26,category:'HVAC'},
  {keyword:'kitchen and bath remodeling near me',searchVol:40,cpc:23.19,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'bryant ac unit',searchVol:30,cpc:9.75,category:'HVAC'},
  {keyword:'stone coated steel roofing',searchVol:40,cpc:16.74,category:'Roofing'},
  {keyword:'galvalume metal roof',searchVol:20,cpc:19.09,category:'Roofing'},
  {keyword:'fascia roof',searchVol:50,cpc:13.81,category:'Roofing'},
  {keyword:'pool refinishing',searchVol:170,cpc:31.55,category:'Pool Services'},
  {keyword:'bath remodeling contractors near me',searchVol:20,cpc:33.84,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'over the top roofing',searchVol:70,cpc:31.11,category:'Roofing'},
  {keyword:'roof pressure cleaning',searchVol:30,cpc:27.63,category:'Roofing'},
  {keyword:'stone coated metal roofing',searchVol:40,cpc:16.74,category:'Roofing'},
  {keyword:'power wash driveway',searchVol:50,cpc:10.46,category:'Pressure Washing'},
  {keyword:'ac units home depot',searchVol:90,cpc:10.17,category:'HVAC'},
  {keyword:'roof washing near me',searchVol:20,cpc:48.0,category:'Roofing'},
  {keyword:'roof coatings',searchVol:20,cpc:15.78,category:'Roofing'},
  {keyword:'pavers for driveway',searchVol:110,cpc:10.82,category:'Concrete'},
  {keyword:'24x24 concrete pavers',searchVol:20,cpc:2.34,category:'Concrete'},
  {keyword:'roof ventilation',searchVol:30,cpc:43.78,category:'Roofing'},
  {keyword:'power washing prices',searchVol:20,cpc:9.69,category:'Pressure Washing'},
  {keyword:'epoxy coating garage floor',searchVol:210,cpc:19.35,category:'Flooring'},
  {keyword:'one hour hvac',searchVol:110,cpc:48.17,category:'HVAC'},
  {keyword:'bathroom tub to shower conversion',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'swimming pool resurfacing',searchVol:170,cpc:31.55,category:'Pool Services'},
  {keyword:'air conditioning units for homes',searchVol:40,cpc:17.92,category:'HVAC'},
  {keyword:'bathroom renovation companies',searchVol:20,cpc:22.2,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'home depot shingles',searchVol:20,cpc:14.64,category:'Roofing'},
  {keyword:'power washing trailer',searchVol:30,cpc:4.7,category:'Pressure Washing'},
  {keyword:'american standard ac units',searchVol:50,cpc:9.56,category:'HVAC'},
  {keyword:'thatched roof',searchVol:20,cpc:12.19,category:'Roofing'},
  {keyword:'tempstar ac',searchVol:20,cpc:26.48,category:'HVAC'},
  {keyword:'kitchen and bathroom remodeling near me',searchVol:40,cpc:23.19,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'kitchen and bathroom',searchVol:50,cpc:10.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'hvacr technicians',searchVol:70,cpc:38.66,category:'HVAC'},
  {keyword:'modified bitumen roof',searchVol:20,cpc:18.12,category:'Roofing'},
  {keyword:'polyaspartic garage floor',searchVol:20,cpc:19.25,category:'Flooring'},
  {keyword:'concrete business near me',searchVol:260,cpc:10.83,category:'Concrete'},
  {keyword:'roof cleaning companies near me',searchVol:30,cpc:17.45,category:'Roofing'},
  {keyword:'air duct sealing',searchVol:20,cpc:19.18,category:'HVAC'},
  {keyword:'pressure washing cost',searchVol:20,cpc:9.69,category:'Pressure Washing'},
  {keyword:'deck building companies near me',searchVol:30,cpc:19.73,category:'Deck & Outdoor'},
  {keyword:'sealing concrete driveway',searchVol:20,cpc:4.11,category:'Concrete'},
  {keyword:'kitchen bathroom remodel',searchVol:30,cpc:19.11,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'new air conditioning unit cost',searchVol:20,cpc:17.95,category:'HVAC'},
  {keyword:'pool decking repair',searchVol:20,cpc:28.62,category:'Pool Services'},
  {keyword:'deck composite',searchVol:90,cpc:4.13,category:'Deck & Outdoor'},
  {keyword:'average cost of bathroom renovation',searchVol:20,cpc:9.65,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'small power washer',searchVol:20,cpc:1.14,category:'Pressure Washing'},
  {keyword:'ac duct',searchVol:30,cpc:23.4,category:'HVAC'},
  {keyword:'split air conditioning units',searchVol:140,cpc:6.52,category:'HVAC'},
  {keyword:'hvac technicians',searchVol:70,cpc:38.66,category:'HVAC'},
  {keyword:'average cost to redo a bathroom',searchVol:20,cpc:9.65,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pressure wash roof',searchVol:30,cpc:27.63,category:'Roofing'},
  {keyword:'deck near me',searchVol:30,cpc:19.73,category:'Deck & Outdoor'},
  {keyword:'swimming pool resurfacing near me',searchVol:110,cpc:42.23,category:'Pool Services'},
  {keyword:'miller air conditioning',searchVol:50,cpc:36.31,category:'HVAC'},
  {keyword:'polyaspartic flooring',searchVol:70,cpc:17.73,category:'Flooring'},
  {keyword:'timbertech deck',searchVol:20,cpc:2.27,category:'Deck & Outdoor'},
  {keyword:'h&c concrete stain',searchVol:20,cpc:2.26,category:'Concrete'},
  {keyword:'gable roof',searchVol:90,cpc:49.0,category:'Roofing'},
  {keyword:'composite roof shingles',searchVol:20,cpc:17.22,category:'Roofing'},
  {keyword:'pressure washing store',searchVol:30,cpc:4.12,category:'Pressure Washing'},
  {keyword:'power wash home',searchVol:20,cpc:10.19,category:'Pressure Washing'},
  {keyword:'pressure washing store near me',searchVol:30,cpc:3.41,category:'Pressure Washing'},
  {keyword:'composite shingles',searchVol:20,cpc:17.22,category:'Roofing'},
  {keyword:'epoxy flooring companies near me',searchVol:70,cpc:23.93,category:'Flooring'},
  {keyword:'kitchen & bath remodeling',searchVol:30,cpc:19.11,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'typical bathroom remodel cost',searchVol:20,cpc:9.65,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'ventless air conditioners',searchVol:20,cpc:2.19,category:'HVAC'},
  {keyword:'metal roof sheeting',searchVol:20,cpc:14.41,category:'Roofing'},
  {keyword:'good pressure washer',searchVol:50,cpc:0.97,category:'Pressure Washing'},
  {keyword:'epoxy resin garage floor',searchVol:210,cpc:19.35,category:'Flooring'},
  {keyword:'pool refinishing cost',searchVol:50,cpc:18.72,category:'Pool Services'},
  {keyword:'driveway pressure cleaning',searchVol:50,cpc:10.46,category:'Pressure Washing'},
  {keyword:'top rated electric pressure washer',searchVol:20,cpc:1.19,category:'Pressure Washing'},
  {keyword:'bathtub renovation cost',searchVol:70,cpc:9.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'bathroom reconstruction',searchVol:390,cpc:28.82,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'kitchen reno cost',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'air handlers',searchVol:70,cpc:11.29,category:'HVAC'},
  {keyword:'shower to bathtub conversion',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'bath renovation companies',searchVol:20,cpc:22.2,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'power wash cost',searchVol:20,cpc:9.69,category:'Pressure Washing'},
  {keyword:'pool decking resurfacing',searchVol:70,cpc:18.5,category:'Pool Services'},
  {keyword:'floor grinding',searchVol:20,cpc:9.75,category:'General Contracting'},
  {keyword:'bathroom renos near me',searchVol:320,cpc:38.05,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'home depot electric pressure washer',searchVol:20,cpc:0.75,category:'Pressure Washing'},
  {keyword:'architectural roof shingles',searchVol:50,cpc:42.08,category:'Roofing'},
  {keyword:'iko roof shingles',searchVol:20,cpc:7.03,category:'Roofing'},
  {keyword:'owens corning roof shingles',searchVol:40,cpc:12.0,category:'Roofing'},
  {keyword:'amazon power washer',searchVol:20,cpc:1.38,category:'Pressure Washing'},
  {keyword:'epoxy garage floor price',searchVol:40,cpc:16.32,category:'Flooring'},
  {keyword:'garage floor covering epoxy',searchVol:210,cpc:19.35,category:'Flooring'},
  {keyword:'air conditioning ductwork',searchVol:30,cpc:23.4,category:'HVAC'},
  {keyword:'ac cool',searchVol:20,cpc:18.67,category:'HVAC'},
  {keyword:'power pressure washer',searchVol:170,cpc:5.72,category:'Pressure Washing'},
  {keyword:'remodel kitchen near me',searchVol:210,cpc:32.58,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'surface cleaners for pressure washers',searchVol:90,cpc:1.42,category:'Pressure Washing'},
  {keyword:'concrete drilling',searchVol:30,cpc:14.11,category:'Concrete'},
  {keyword:'tempstar air conditioner',searchVol:20,cpc:26.48,category:'HVAC'},
  {keyword:'pitched roof',searchVol:20,cpc:32.03,category:'Roofing'},
  {keyword:'top electric pressure washers',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'best rated electric pressure washer',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'kitchen redesign cost',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'bathroom refinishers',searchVol:30,cpc:22.14,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'air conditioning ducts',searchVol:30,cpc:23.4,category:'HVAC'},
  {keyword:'cooling air conditioner',searchVol:20,cpc:18.67,category:'HVAC'},
  {keyword:'honda powered pressure washer',searchVol:30,cpc:1.07,category:'Pressure Washing'},
  {keyword:'top rated electric power washers',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'cleaning driveway',searchVol:30,cpc:6.02,category:'Pressure Washing'},
  {keyword:'small bathroom redo',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pressure washer ryobi',searchVol:260,cpc:0.92,category:'Pressure Washing'},
  {keyword:'swimming pool resurfacing cost',searchVol:50,cpc:18.72,category:'Pool Services'},
  {keyword:'roof tiling',searchVol:90,cpc:19.28,category:'Roofing'},
  {keyword:'bathroom remodels for small bathrooms',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'kitchen remodel prices',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'glass reinforced concrete',searchVol:20,cpc:15.95,category:'Concrete'},
  {keyword:'kitchen renos near me',searchVol:210,cpc:32.58,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'ryobi electric power washer',searchVol:40,cpc:0.5,category:'Pressure Washing'},
  {keyword:'soft washer',searchVol:40,cpc:2.9,category:'Pressure Washing'},
  {keyword:'best rated electric power washer',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'painted concrete patio',searchVol:50,cpc:2.44,category:'Concrete'},
  {keyword:'good power washer',searchVol:50,cpc:0.97,category:'Pressure Washing'},
  {keyword:'aircon ducting',searchVol:30,cpc:23.4,category:'General Contracting'},
  {keyword:'greenwork pressure washer',searchVol:70,cpc:1.03,category:'Pressure Washing'},
  {keyword:'concrete pavement',searchVol:70,cpc:5.93,category:'Concrete'},
  {keyword:'garage floor flooring',searchVol:70,cpc:19.35,category:'Flooring'},
  {keyword:'pressure cleaning companies',searchVol:50,cpc:27.54,category:'Pressure Washing'},
  {keyword:'roofing installation',searchVol:40,cpc:64.0,category:'Roofing'},
  {keyword:'pressure pros',searchVol:40,cpc:2.44,category:'General Contracting'},
  {keyword:'epoxy painting',searchVol:40,cpc:2.07,category:'Handyman Services'},
  {keyword:'pressure cleaning business',searchVol:20,cpc:13.0,category:'Pressure Washing'},
  {keyword:'kitchen reno near me',searchVol:210,cpc:32.58,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'good electric pressure washer',searchVol:90,cpc:1.36,category:'Pressure Washing'},
  {keyword:'ryobi pressure washer electric',searchVol:40,cpc:0.5,category:'Pressure Washing'},
  {keyword:'painting garage floor epoxy',searchVol:20,cpc:2.87,category:'Flooring'},
  {keyword:'epoxy floor painting',searchVol:30,cpc:2.83,category:'Flooring'},
  {keyword:'bathroom redesign cost',searchVol:70,cpc:9.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'best water pressure washer',searchVol:50,cpc:0.97,category:'Pressure Washing'},
  {keyword:'epoxy finish garage floor',searchVol:210,cpc:16.8,category:'Flooring'},
  {keyword:'small bathroom redesign',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'converting a tub into a shower',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'all clean pressure washing',searchVol:70,cpc:7.6,category:'Pressure Washing'},
  {keyword:'kitchen bathroom remodel near me',searchVol:40,cpc:23.19,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'kitchen and baths',searchVol:50,cpc:10.1,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'epoxy coating garage floor cost',searchVol:40,cpc:16.32,category:'Flooring'},
  {keyword:'bathroom remodel bathtub',searchVol:390,cpc:28.82,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'small bathroom renos',searchVol:50,cpc:8.6,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'daikin ac company',searchVol:110,cpc:12.12,category:'HVAC'},
  {keyword:'converting shower to tub',searchVol:30,cpc:30.83,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'commercial pressure cleaning',searchVol:90,cpc:6.68,category:'Pressure Washing'},
  {keyword:'concrete slabs price',searchVol:20,cpc:6.43,category:'Concrete'},
  {keyword:'epoxyflooring',searchVol:90,cpc:17.33,category:'Flooring'},
  {keyword:'mitsubishi air cond',searchVol:20,cpc:4.61,category:'HVAC'},
  {keyword:'price to resurface pool',searchVol:50,cpc:18.72,category:'Pool Services'},
  {keyword:'affordable pressure washer',searchVol:20,cpc:11.0,category:'Pressure Washing'},
  {keyword:'kitchen renovation prices',searchVol:50,cpc:10.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pool recoating',searchVol:170,cpc:31.55,category:'Pool Services'},
  {keyword:'pressure washing your house',searchVol:20,cpc:10.19,category:'Pressure Washing'},
  {keyword:'azek decks',searchVol:20,cpc:1.76,category:'Deck & Outdoor'},
  {keyword:'meltini kitchen & bath',searchVol:50,cpc:18.34,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'painting and flooring',searchVol:20,cpc:19.4,category:'Flooring'},
  {keyword:'abcsupply',searchVol:1000,cpc:9.11,category:'General Contracting'},
  {keyword:'wash pressure',searchVol:1000,cpc:3.3,category:'Pressure Washing'},
  {keyword:'average bath remodel cost',searchVol:20,cpc:9.65,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'honda water pressure washer',searchVol:30,cpc:1.07,category:'Pressure Washing'},
  {keyword:'kitchen and remodeling',searchVol:30,cpc:40.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pressure washer pressure',searchVol:1000,cpc:3.3,category:'Pressure Washing'},
  {keyword:'renov kitchen',searchVol:30,cpc:40.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'deck above ground pool',searchVol:70,cpc:2.51,category:'Pool Services'},
  {keyword:'price to resurface a pool',searchVol:50,cpc:18.72,category:'Pool Services'},
  {keyword:'decks with pools',searchVol:70,cpc:10.01,category:'Pool Services'},
  {keyword:'roof apex',searchVol:20,cpc:31.59,category:'Roofing'},
  {keyword:'heating ventilation and air conditioning',searchVol:390,cpc:42.0,category:'HVAC'},
  {keyword:'kitchen remodel remodeling',searchVol:30,cpc:40.0,category:'Kitchen & Bathroom Remodeling'},
  {keyword:'pool re surfacing',searchVol:170,cpc:31.55,category:'Pool Services'},
];
